version: '1.0.0'
services:
  mongo:
    container_name: mongo
    image: mongo:4.0-xenial
    volumes:
      - data:/data/db
  flask:
    container_name: flask
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
       - mongo

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  data:
